version: "3"
services:
  database:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
